name = "Turkie"
uuid = "8156cc02-0533-41cd-9345-13411ebe105f"
authors = ["Th√©o Galy-Fajou <theo.galyfajou@gmail.com> and contributors"]
version = "0.1.15"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
ColorSchemes = "3"
Colors = "0.13"
KernelDensity = "0.6"
MCMCChains = "7"
Makie = "0.23, 0.24"
OnlineStats = "1.5"
Turing = "0.39, 0.40"
julia = "1.10"
