name = "Turkie"
uuid = "8156cc02-0533-41cd-9345-13411ebe105f"
authors = ["Theo Galy-Fajou <theo.galyfajou@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DynamicPPL = "366bfd00-2699-11ea-058f-f148b4cae6d8"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"

[compat]
AbstractPlotting = "0.12, 0.13"
ColorSchemes = "3.10"
Colors = "0.12"
DynamicPPL = "0.9, 0.10"
KernelDensity = "0.5, 0.6"
OnlineStats = "1.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
